version: '3'
services:
  excalidraw-alternative-store:
    image: ghcr.io/cocreators-ee/excalidraw-alternative-store
    restart: unless-stopped
    ports:
      - '4400:8080'
    environment:
      PORT: 8080
      ALLOWED_CORS_ORIGINS: https://your.excalidraw.domain
    volumes:
      - ./storage:/src/storage

  excalidraw-room:
    image: excalidraw/excalidraw-room
    restart: unless-stopped
    ports:
      - '4401:4401'
    environment:
      PORT: 4401
      CORS_ORIGIN: https://your.excalidraw.domain

  excalidraw:
    image: ghcr.io/cocreators-ee/excalidraw
    restart: unless-stopped
    ports:
      - '4402:4402'
    environment:
      VITE_APP_BACKEND_V2_GET_URL: https://your.excalidraw-store.domain/api/v2/
      VITE_APP_BACKEND_V2_POST_URL: https://your.excalidraw-store.domain/api/v2/post/
      VITE_APP_WS_SERVER_URL: https://your.excalidraw-room.domain
